2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Configure stats pid to 498833
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Loading settings from /home/local/ASUAD/aravik13/.config/wandb/settings
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Loading settings from /data/data/arrv/ThinkTuning_v1/wandb/settings
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/data/data/arrv/ThinkTuning_v1/train.py', 'program': '/data/data/arrv/ThinkTuning_v1/train.py'}
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_init.py:_log_setup():532] Logging user logs to /data/data/arrv/ThinkTuning_v1/wandb/run-20241007_230301-e7kjozdl/logs/debug.log
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_init.py:_log_setup():533] Logging internal logs to /data/data/arrv/ThinkTuning_v1/wandb/run-20241007_230301-e7kjozdl/logs/debug-internal.log
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_init.py:init():617] calling init triggers
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-07 23:03:01,937 INFO    MainThread:498833 [wandb_init.py:init():667] starting backend
2024-10-07 23:03:01,938 INFO    MainThread:498833 [wandb_init.py:init():671] sending inform_init request
2024-10-07 23:03:01,941 INFO    MainThread:498833 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-07 23:03:01,941 INFO    MainThread:498833 [wandb_init.py:init():684] backend started and connected
2024-10-07 23:03:01,947 INFO    MainThread:498833 [wandb_init.py:init():779] updated telemetry
2024-10-07 23:03:01,952 INFO    MainThread:498833 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-07 23:03:02,044 ERROR   MainThread:498833 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-07 23:03:02,045 ERROR   MainThread:498833 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/data/data/arrv/envs/tv1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
           ^^^^^^^^^
  File "/data/data/arrv/envs/tv1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-10-07 23:03:02,144 WARNING MsgRouterThr:498833 [router.py:message_loop():77] message_loop has been closed
